CREATE SCHEMA jhomework;
GRANT USAGE ON SCHEMA jhomework TO pa_admin;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA jhomework TO pa_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA jhomework TO pa_admin;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA jhomework TO pa_admin;
GRANT ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA jhomework TO pa_admin;

GRANT CREATE ON SCHEMA jhomework TO pa_admin;

ALTER DEFAULT PRIVILEGES IN SCHEMA jhomework
GRANT ALL PRIVILEGES ON TABLES TO pa_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA jhomework
GRANT ALL PRIVILEGES ON SEQUENCES TO pa_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA jhomework
GRANT ALL PRIVILEGES ON FUNCTIONS TO pa_admin;
ALTER DEFAULT PRIVILEGES IN SCHEMA jhomework
GRANT ALL PRIVILEGES ON TYPES TO pa_admin;

REVOKE ALL ON SCHEMA public FROM pa_admin;